### ISSUE TITLE
Can't build on node v0.8.0

### ISSUE THREAD

**Issue by muirmanders** [chrisdew/protobuf#8]
I see this error when trying to build the module on node v0.8.0 (Mac OS X 10.7):

```
 Checking for program g++ or c++          : /usr/bin/g++ 
 Checking for program cpp                 : /usr/bin/cpp 
 Checking for program ar                  : /usr/bin/ar 
 Checking for program ranlib              : /usr/bin/ranlib 
 Checking for g++                         : ok  
 Checking for node path                   : not found 
 Checking for node prefix                 : ok /Users/muir/.nvm/v0.8.0 
 'configure' finished successfully (0.120s)
 'clean' finished successfully (0.011s)
 Waf: Entering directory `/Users/muir/projects/nearbuy/protobuf/build'
 [1/3] cxx: protobuf_for_node.cc -> build/Release/protobuf_for_node_1.o
 [2/3] cxx: addon.cc -> build/Release/addon_1.o
 ../protobuf_for_node.cc: In static member function ‘static void protobuf_for_node::WrappedService::AsyncInvocation::Init()’:
 ../protobuf_for_node.cc:549: error: invalid conversion from ‘void (*)(ev_async*, int)’ to ‘void (*)(ev_loop*, ev_async*, int)’
 ../protobuf_for_node.cc: In static member function ‘static void protobuf_for_node::WrappedService::AsyncInvocation::Done(protobuf_for_node::WrappedService::AsyncInvocation*)’:
 ../protobuf_for_node.cc:605: error: cannot convert ‘ev_async*’ to ‘ev_loop*’ for argument ‘1’ to ‘void ev_async_send(ev_loop*, ev_async*)’
 ../protobuf_for_node.cc: In static member function ‘static int protobuf_for_node::WrappedService::AsyncInvocation::Returned(eio_req*)’:
 ../protobuf_for_node.cc:615: error: cannot convert ‘ev_async*’ to ‘ev_loop*’ for argument ‘1’ to ‘void ev_async_start(ev_loop*, ev_async*)’
 ../protobuf_for_node.cc: In static member function ‘static void protobuf_for_node::WrappedService::AsyncInvocation::InvokeAsyncCallbacks(ev_async*, int)’:
 ../protobuf_for_node.cc:639: error: cannot convert ‘ev_async*’ to ‘ev_loop*’ for argument ‘1’ to ‘void ev_async_stop(ev_loop*, ev_async*)’
 Waf: Leaving directory `/Users/muir/projects/nearbuy/protobuf/build'
 Build failed:  -> task failed (err #1): 
    {task: cxx protobuf_for_node.cc -> protobuf_for_node_1.o}
```

The problem is that the new ev-emul.h undefines a bunch of important EV_MULTIPLICITY-related macros (in particular, EV_P_). I'm not sure exactly why it does this, but the solution is probably to switch protobuf to uv instead of ev.
